var constants = {

	BARBELL_SQUAT: 'Barbell Squat',
	BARBELL_SQUAT_WEIGHT: 125,

	BARBELL_BENCH_PRESS_MEDIUM_GRIP: "Barbell Bench Press - Medium Grip",
	BARBELL_BENCH_PRESS_MEDIUM_GRIP_WEIGHT: 75,

	BENT_OVER_BARBELL_ROW: "Bent Over Barbell Row",
	BENT_OVER_BARBELL_ROW_WEIGHT: 60,

	SIDE_LATERAL_RAISE: "Side Lateral Raise",
	SIDE_LATERAL_RAISE_WEIGHT: 20 ,

	FRONT_BARBELL_SQUAT: "Front Barbell Squat",
	FRONT_BARBELL_SQUAT_WEIGHT: 100,

	SEATED_BARBELL_MILITARY_PRESS: "Seated Barbell Military Press",
	SEATED_BARBELL_MILITARY_PRESS_WEIGHT: 65,

	BARBELL_DEADLIFT: "Barbell Deadlift",
	BARBELL_DEADLIFT_WEIGHT: 90,

	BARBELL_CURL: "Barbell Curl",
	BARBELL_CURL_WEIGHT: 20,

	SEATED_TRICEPS_PRESS: "Seated Triceps Press",
	SEATED_TRICEPS_PRESS_WEIGHT: 30,

	DUMBBELL_BENCH_PRESS: "Dumbbell Bench Press",
	DUMBBELL_BENCH_PRESS_WEIGHT: 100,

	BUTTERFLY: "Butterfly",
	BUTTERFLY_WEIGHT: 30,

	INCLINE_BENCH_PULL: "Incline Bench Pull",
	INCLINE_BENCH_PULL_WEIGHT: 60,

	STANDING_CALF_RAISE: "Standing Calf Raise",
	STANDING_CALF_RAISE_WEIGHT: 20,

	SEATED_CALF_RAISE: "Seated Calf Raise",
	SEATED_CALF_RAISE_WEIGHT: 30,

	DUMBBELL_BICEP_CURL: "Dumbbell Bicep Curl",
	DUMBBELL_BICEP_CURL_WEIGHT: 20,

	CABLE_LYING_TRICEPS_EXTENSION: "Cable Lying Triceps Extension",
	CABLE_LYING_TRICEPS_EXTENSION_WEIGHT: 20,
	
	HAMMER_CURLS: "Hammer Curls",
	HAMMER_CURLS_WEIGHT: 20,
	STANDING_BICEPS_CABLE_CURL: "Standing Bicep Cable Curls",
	STANDING_BICEPS_CABLE_CURL_WEIGHT: 20,
	CLOSE_GRIP_BARBELL_BENCH_PRESS: "Close Grip Barbell Bench Press",
	CLOSE_GRIP_BARBELL_BENCH_PRESS_WEIGHT: 80,
	CABLE_ROPE_OVERHEAD_TRICEPS_EXTENSION: "Cable Rope Overhead Triceps Extension",
	CABLE_ROPE_OVERHEAD_TRICEPS_EXTENSION_WEIGHT: 30,
	LEG_PRESS: "Leg Press",
	LEG_PRESS_WEIGHT: 150,
	LEG_EXTENSIONS: "Leg Extensions",
	LEG_EXTENSIONS_WEIGHT: 30,
	INCLINE_DUMBBELL_BENCH_PRESS: "Incline Dumbbell Bench Press",
	INCLINE_DUMBBELL_BENCH_PRESS_WEIGHT: 60,
	CABLE_CROSSOVER: "Cable Crossover",
	CABLE_CROSSOVER_WEIGHT: 30,
	WIDE_GRIP_LAT_PULLDOWN: "Wide Grip Lat Pulldown",
	WIDE_GRIP_LAT_PULLDOWN_WEIGHT: 80,
	SEATED_CABLE_ROW: "Seated Cable Row",
	SEATED_CABLE_ROW_WEIGHT: 70,
	DUMBBELL_SHOULDER_PRESS: "Dumbbell Shoulder Press",
	DUMBBELL_SHOULDER_PRESS_WEIGHT: 60,
	FRONT_DUMBBELL_RAISE: "Front Dumbbell Raise",
	FRONT_DUMBBELL_RAISE_WEIGHT: 20,
	SIDE_LATERAL_RAISE: "Side Lateral Raise",
	SIDE_LATERAL_RAISE_WEIGHT: 15,
	INCLINE_DUMBBELL_CURL: "Incline Dumbbell Curl",
	INCLINE_DUMBBELL_CURL_WEIGHT: 20,


	PULLUPS: "Pull-ups",
	PULLUPS_WEIGHT: 0,

	SITUPS: "Sit-ups",
	SITUPS_WEIGHT: 0,

	HANGING_LEG_RAISE: "Hanging Leg Raise",
	HANGING_LEG_RAISE_WEIGHT: 0,

	FIVE_PERCENT_MULTIPLIER: 1.05,

	STRING: 'string',
	NUMBER: 'number',
	OBJECT: 'object',
	BOOL: 'bool'

}

module.exports = constants;