var constants = {

	BARBELL_SQUAT: 'Barbell Squat',
	BARBELL_SQUAT_WEIGHT: 125,

	BARBELL_BENCH_PRESS_MEDIUM_GRIP: "Barbell Bench Press - Medium Grip",
	BARBELL_BENCH_PRESS_MEDIUM_GRIP_WEIGHT: 75,

	BENT_OVER_BARBELL_ROW: "Bent Over Barbell Row",
	BENT_OVER_BARBELL_ROW_WEIGHT: 60,

	SIDE_LATERAL_RAISE: "Side Lateral Raise",
	SIDE_LATERAL_RAISE_WEIGHT: 20 ,

	FRONT_BARBELL_SQUAT: "Front Barbell Squat",
	FRONT_BARBELL_SQUAT_WEIGHT: 100,

	SEATED_BARBELL_MILITARY_PRESS: "Seated Barbell Military Press",
	SEATED_BARBELL_MILITARY_PRESS_WEIGHT: 65,

	BARBELL_DEADLIFT: "Barbell Deadlift",
	BARBELL_DEADLIFT_WEIGHT: 90,

	BARBELL_CURL: "Barbell Curl",
	BARBELL_CURL_WEIGHT: 20,

	SEATED_TRICEPS_PRESS: "Seated Triceps Press",
	SEATED_TRICEPS_PRESS_WEIGHT: 30,


	PULLUPS: "Pull-ups",
	PULLUPS_WEIGHT: 0,

	SITUPS: "Sit-ups",
	SITUPS_WEIGHT: 0,

	FIVE_PERCENT_MULTIPLIER: 1.05,

	STRING: 'string',
	NUMBER: 'number',
	OBJECT: 'object',
	BOOL: 'bool'

}

module.exports = constants;